### ISSUE TITLE
Handle responses that aren't valid JSON more gracefully

### ISSUE THREAD

**Issue by lennyburdette** [Zappos/zappos-rubygem#5]
When the API really doesn't want to cooperate, the body of the response may not be JSON. The JSON parser throws an exception and it's hard to inspect or recover from the error.

**Comment by makenai** [comment]
I can reproduce this one:

JSON::ParserError - A JSON text must at least contain two octets!:
 /Library/Ruby/Gems/1.8/gems/json-1.4.6/lib/json/common.rb:146:in `initialize'
 /Library/Ruby/Gems/1.8/gems/json-1.4.6/lib/json/common.rb:146:in`new'
 /Library/Ruby/Gems/1.8/gems/json-1.4.6/lib/json/common.rb:146:in `parse'
 /Library/Ruby/Gems/1.8/bundler/gems/zappos-f8387ccd4878/lib/zappos/response.rb:13:in`initialize'
 /Library/Ruby/Gems/1.8/bundler/gems/zappos-f8387ccd4878/lib/zappos/base_client.rb:12:in `new'
 /Library/Ruby/Gems/1.8/bundler/gems/zappos-f8387ccd4878/lib/zappos/base_client.rb:12:in`execute'

**Comment by makenai** [comment]
Fixed in 0.3.0
